config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only:[:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian), message: "Sorry that's not a valid category."}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :set_restaurant

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  # def set_restaurant
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  # end


  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="content-container"></div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3270&q=80);">
  <div class="container">
    <h1>Yelp MVP reviews <strong>the best</strong> restaurants <strong>just for you </strong>!</h1>
    <p>Make sure you know your food will be great before leaving home.</p>
  </div>
</div>
<div class="container my-4">
  <div class= "row d-flex justify-content-around">
    <% @restaurants.each do |restaurant|  %>
      <div class= "card">
        <h2><%=restaurant.name %></h2>
        <p class= "title" ><%= restaurant.address %></p>
        <p><%= restaurant.category.capitalize %></p>
        <%= link_to "More..", restaurant_path(restaurant), class: 'my-button'  %>
      </div>
   <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class= "container form-group">
  <%= simple_form_for [ @restaurant ] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class= "container d-flex d-flex justify-content-between">
  <div class= "card" id= "show-card">
    <img src="https://picsum.photos/seed/picsum/150">
    <h2><%= @restaurant.name %></h2>
    <h2 class= "title"><%= @restaurant.address %></h2>
    <p><%= @restaurant.category.capitalize %></p>
    <ul class= "list-inline justify-content-around">
      <li class="list-inline-item"><%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "a" %>     *
      <li class="list-inline-item"><%= link_to 'Back', restaurants_path, class: "a" %>    *
      <li class="list-inline-item"><%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class: "a" %>
    </ul>
  </div>
  <ul class= "list-group ml-2 align-self-start" id= "list">
    <% @restaurant.reviews.each do |review| %>
      <li class= "list-group-item"><%= review.content.capitalize %></li>
      <li class= "list-group-item">Rating: <%= review.rating %></li>
    <% end %>
  </ul>
</div>

app/views/reviews/new.html.erb
<div class= "container form-group">
  <%= simple_form_for [ @restaurant, @review ] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, placeholder: "Please choose a number bewteen 0-5" %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  <%= link_to 'Back', restaurants_path, class: "a" %>
</div>